server:
  port: 8080
spring:
  profiles:
    active: dev
  cloud:
    ai:
      tongyi:
        api-key: sk-05177c3dc5c04be4a30919a227aeaace
        chat:
          options:
            model: deepseek-r1
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1
          temperature: 0.7
        enabled: true

dify:
  api:
    url: https://api.dify.ai/v1
    key: dataset-FFvr4WNU37aTm780DtKMtIbN

milvus:
  host: localhost
  port: 19530